title: EGRAPHS Community
description: >- # this means to ignore newlines until "baseurl:"
  EGRAPHS Community
baseurl: ""
url: "https://egraphs.org"

# publish posts (talks) with dates in the future
future: true

permalink: /:categories/:year-:month-:day-:title
# permalink: /:categories/:title
# markdown: kramdown
# collections:
#   papers:
#     permalink: /:collection/:name:output_ext
#     output: true
